name: OnlineDonators
version: '1.0'
main: me.durqznohh.donators.OnlineDonators
api-version: 1.13
commands:
  onlinedonators:
    description: Online donators
    aliases: [donators]
  odr:
    description: Reload the config